# Generated by Django 5.1.3 on 2024-12-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100, unique=True)),
                ('Pwd', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='employee_images/')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Mobile', models.CharField(max_length=15)),
                ('Designation', models.CharField(max_length=50)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('Course', models.CharField(max_length=100)),
                ('Createdate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
